version: '3'

networks:
  demo:

services:
  mariadb-kotlin:
    image: mariadb:latest
    container_name: mariadb-kotlin
    ports:
      - 6612:3306
    environment:
      - MARIADB_DATABASE=master
      - MARIADB_ROOT_PASSWORD=changeme
    networks:
      - demo
    restart: always
  mariadb-keycloak:
    image: mariadb:latest
    container_name: mariadb-keycloak
    ports:
      - 6613:3306
    environment:
      - MARIADB_DATABASE=keycloak_db
      - MARIADB_ROOT_PASSWORD=changeme
    networks:
      - demo
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: keycloak
    environment:
      DB_VENDOR: MARIADB
      DB_ADDR: mariadb-keycloak
      DB_DATABASE: keycloak_db
      DB_USER: root
      DB_PASSWORD: changeme
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
    ports:
      - 8080:8080
    depends_on:
      - mariadb-keycloak
    networks:
      - demo
    restart: always
